---
title: "20201102-p8133_computingassignment2_jsg2145"
author: "Jared Garfinkel"
date: "11/2/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(dfcrm)
knitr::opts_chunk$set(
	echo = FALSE,
	warning = FALSE,
	message = FALSE,
	cache = TRUE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

### Simulate the data

```{r}
set.seed(719)
data = runif(50000) %>% 
  tibble() %>% 
  rename("value" = ".")

data %>% 
  pull(value) %>% 
  hist(.)
```
# Question 1

```{r, echo = TRUE}
design3plus3 = function(n = 10, p = c(0.017, 0.043, 0.1, 0.22, 0.41)) {
  ntox = 0
  i = 1
  j = 1
  l = 1
  res = vector(mode = "list", length = 30)
  fin = NULL
  for (l in 1:n) {
    ntox = 0
    while (ntox < 2 & i < 6) {
      ntox = 0
      for (k in (3*(j-1)+1):(3*(j-1)+3)) {
        ntox = if_else(pull(data, value)[[k]] < p[[i]], (ntox + 1), ntox)
        res = rbind(res, cbind(ntox, i, k, l))
      }
      if(ntox == 1) {
        for (k in (3*j+1):(3*j+3)) {
          ntox = if_else(pull(data, value)[[k]] < p[[i]], (ntox + 1), ntox)
          res = rbind(res, cbind(ntox, i, k, l))
        }
        j = j + 1
      }
      # else {
      #   ntox = 0
      #   i = i + 1
      #   j = j + 1
      # }
      # ntox = 0
      i = i + 1
      j = j + 1
    }
    if (ntox < 2) {
      i = i - 1
    }
    fin[[l]] = res %>%
      data.frame() %>%
      tibble() %>%
      unnest(cols = c(ntox, i, k, l)) %>%
      
      summarize(ntox = last(ntox),
                i = last(i),
                k = last(k),
                l = last(l))
    i = 1
    j = k/3 + 1
    ntox = 0
    l = l + 1
  }
  fin = bind_rows(fin)
  return(fin)
}
```


```{r}
design3plus3_full = function(n = 10, p = c(0.017, 0.043, 0.1, 0.22, 0.41)) {
  ntox = 0
  i = 1
  j = 1
  l = 1
  res = vector(mode = "list", length = 30)
  fin = NULL
  for (l in 1:n) {
    ntox = 0
    while (ntox < 2 & i < 6) {
      ntox = 0
      for (k in (3*(j-1)+1):(3*(j-1)+3)) {
        ntox = if_else(pull(data, value)[[k]] < p[[i]], (ntox + 1), ntox)
        res = rbind(res, cbind(ntox, i, k, l))
      }
      if(ntox == 1) {
        for (k in (3*j+1):(3*j+3)) {
          ntox = if_else(pull(data, value)[[k]] < p[[i]], (ntox + 1), ntox)
          res = rbind(res, cbind(ntox, i, k, l))
        }
        j = j + 1
      }
      # else {
      #   ntox = 0
      #   i = i + 1
      #   j = j + 1
      # }
      # ntox = 0
      i = i + 1
      j = j + 1
    }
    if (ntox < 2) {
      i = i - 1
    }
    i = 1
    j = k/3 + 1
    ntox = 0
    l = l + 1
  }
  return(res)
}
```

```{r}
sum_finl = function(df = finl_df) {
  sum_finl = df %>%
    summarize(`1` = sum(i == 1)/n(),
              `2` = sum(i == 2)/n(),
              `3` = sum(i == 3)/n(),
              `4` = sum(i == 4)/n(),
              `5` = sum(i == 5)/n()) %>% 
    pivot_longer(cols = c(1:5), values_to = "3+3_value", names_to = "i") %>% 
    tibble() %>% 
    mutate(i = as.numeric(i))
  return(sum_finl)
}
```

### pi = c(0.017, 0.043, 0.1, 0.22, 0.41)

```{r, cache = TRUE}
finl_df = design3plus3()
finl_df_full = design3plus3_full()
sum_finl_df = sum_finl()
```

```{r}
slide12_maker = function(df = finl_df_full, n = 10) {
  finl_df_full %>%
    data.frame() %>% 
    unnest() %>% 
    tibble() %>% 
    group_by(i) %>% 
    summarize(sum_i = sum(i == i)/n,
              sum_ntox = last(ntox)/n) %>% 
    left_join(sum_finl_df, by = "i") %>% 
    select(-i) %>% 
    t() %>% 
    data.frame() %>% 
    tibble(variable = c("no_patients", "mean_DLT", "selection_prob")) %>% 
    select(variable, everything()) %>% 
    rename("1" = "X1",
           "2" = "X2",
           "3" = "X3",
           "4" = "X4",
           "5" = "X5")
}
```

```{r}
slide12_maker()
```


```{r}
finl_df %>% 
  pull(i) %>% 
  hist(breaks = c(0:5))
```


# Question 2

## Part a

### pi = c(0.10, 0.22, 0.41, 0.64, 0.81)

```{r, cache = TRUE}
finl_df1 = design3plus3(p = c(0.10, 0.22, 0.41, 0.64, 0.81))
```

```{r}
finl_df1 %>%
  pull(i) %>%
  hist(breaks = c(0:5))
```

## Part b

### pi = c(0.043, 0.10, 0.22, 0.41, 0.64)

```{r, cache = TRUE}
finl_df2 = design3plus3(p = c(0.043, 0.10, 0.22, 0.41, 0.64))
```

```{r}
finl_df2 %>%
  pull(i) %>%
  hist(breaks = c(0:5))
```

## Part c

### pi = c(0.007, 0.017, 0.043, 0.10, 0.22)

```{r, cache = TRUE}
finl_df3 = design3plus3(p = c(0.007, 0.017, 0.043, 0.10, 0.22))
```

```{r}
finl_df3 %>%
  pull(i) %>%
  hist(breaks = c(0:5))
```

## Part d

### pi = c(0.003, 0.007, 0.017, 0.043, 0.10)

```{r, cache = TRUE}
finl_df4 = design3plus3(p = c(0.003, 0.007, 0.017, 0.043, 0.10))
```

```{r}
finl_df4 %>%
  pull(i) %>%
  hist(breaks = c(0:5))
```

# Question 3

Given:

n = 31
p = 0.1
K = 5

Design a CRM.

$\delta$-sensitivity

Step 1
```{r}

d = seq(0.01, .24, by = .01)
p0 = vector(mode = "list", length = 24)
res = NULL
for (i in 1:24) {
  p0[[i]] <- getprior(d[[i]], 0.1, 3, 5, model="logistic")
}

prior = p0[[3]]
```

I choose p = 0.03 because it is between 0.02 and 0.04, the ideal candidates for $\delta$-sensitivity with N = 31.

Step 2

## Part a

### p = 0.017, 0.043, 0.1, 0.22, 0.41

```{r, results = "hide"}
crm_output = crmsim(c(0.017, 0.043, 0.1, 0.22, 0.41), c(prior[[1]], prior[[2]], prior[[3]], prior[[4]], prior[[5]]), 0.1, 31, 3, nsim = 100, model = "logistic")
```

```{r}
crm_output$MTD %>% 
  plot(type = "h")
```

```{r}
sum_finl_df = sum_finl(finl_df)
crm_df = crm_output$MTD %>% 
  data.frame() %>% 
  tibble() %>% 
  rename("crm_value" = ".")
comp_df = sum_finl_df %>% 
  bind_cols(crm_df)
comp_df %>% 
  knitr::kable(caption = "p = 0.017, 0.043, 0.1, 0.22, 0.41")
```

### p = 0.10, 0.22, 0.41, 0.64, 0.81

```{r, results = "hide"}
crm_output1 = crmsim(c(0.10, 0.22, 0.41, 0.64, 0.81), c(prior[[1]], prior[[2]], prior[[3]], prior[[4]], prior[[5]]), 0.1, 31, 3, nsim = 100, model = "logistic")
```

```{r}
crm_output1$MTD %>% 
  plot(type = "h")
```

```{r}
sum_finl1 = sum_finl(finl_df1)
crm_df1 = crm_output1$MTD %>% 
  data.frame() %>% 
  tibble() %>% 
  rename("crm_value" = ".")
comp_df1 = sum_finl1 %>% 
  bind_cols(crm_df1)
comp_df1 %>% 
    knitr::kable(caption = "p = 0.10, 0.22, 0.41, 0.64, 0.81")
```

### p = 0.043, 0.10, 0.22, 0.41, 0.64

```{r, results = "hide"}
crm_output2 = crmsim(c(0.043, 0.10, 0.22, 0.41, 0.64), c(prior[[1]], prior[[2]], prior[[3]], prior[[4]], prior[[5]]), 0.1, 31, 3, nsim = 100, model = "logistic")
```

```{r}
crm_output2$MTD %>% 
  plot(type = "h")
```

```{r}
sum_finl2 = sum_finl(finl_df2)
crm_df2 = crm_output2$MTD %>% 
  data.frame() %>% 
  tibble() %>% 
  rename("crm_value" = ".")
comp_df2 = sum_finl2 %>% 
  bind_cols(crm_df2)
comp_df1 %>% 
    knitr::kable(caption = "p = 0.043, 0.10, 0.22, 0.41, 0.64")
```

### p = 0.007, 0.017, 0.043, 0.10, 0.22

```{r, results = "hide"}
crm_output3 = crmsim(c(0.007, 0.017, 0.043, 0.10, 0.22), c(prior[[1]], prior[[2]], prior[[3]], prior[[4]], prior[[5]]), 0.1, 31, 3, nsim = 100, model = "logistic")
```

```{r}
crm_output3$MTD %>% 
  plot(type = "h")
```

```{r}
sum_finl3 = sum_finl(finl_df3)
crm_df3 = crm_output3$MTD %>% 
  data.frame() %>% 
  tibble() %>% 
  rename("crm_value" = ".")
comp_df3 = sum_finl3 %>% 
  bind_cols(crm_df3)
comp_df3 %>% 
    knitr::kable(caption = "p = 0.007, 0.017, 0.043, 0.10, 0.22")
```

### p = 0.003, 0.007, 0.017, 0.043, 0.10

```{r, results = "hide"}
crm_output4 = crmsim(c(0.003, 0.007, 0.017, 0.043, 0.10), c(prior[[1]], prior[[2]], prior[[3]], prior[[4]], prior[[5]]), 0.1, 31, 3, nsim = 100, model = "logistic")
```

```{r}
crm_output4$MTD %>% 
  plot(type = "h")
```

```{r}
sum_finl4 = sum_finl(finl_df4)
crm_df4 = crm_output4$MTD %>% 
  data.frame() %>% 
  tibble() %>% 
  rename("crm_value" = ".")
comp_df4 = sum_finl4 %>% 
  bind_cols(crm_df4)
comp_df4 %>% 
    knitr::kable(caption = "p = 0.003, 0.007, 0.017, 0.043, 0.10")
```





